[package]
name = "actix-web-rest"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"
desciption = "Opiniated toolkit to build restful API using actix-web."
documentation = "https://docs.rs/actix-web-rest"
repository = "https://github.com/negrel/actix-web-rest"
readme = "../README.md"
keywords = ["web"]

[lib]
name = "actix_web_rest"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web-rest-macros = { path = "../actix-web-rest-macros/" }
actix-web = { workspace = true }
http = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
strum = { version = "0.24", features = ["derive"] }
